# Generated by Django 5.2 on 2025-05-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio_actual', models.FloatField()),
                ('prediccion', models.FloatField()),
                ('diferencia', models.FloatField()),
                ('tendencia', models.CharField(max_length=50)),
                ('modelo_usado', models.CharField(default='modelo_online', max_length=50)),
            ],
        ),
    ]
